using System;
using System.Collections.Generic;
using NUnit.Framework;
using Moq;

[TestFixture]
class BazTest
{
    private Baz baz;
    [SetUp]
    public void SetUp()
    {
        baz = new Baz();
    }

    [Test]
    public void TestFunction1()
    {
        baz.TestFunction1();
        Assert.Fail("autogenerated");
    }

    [Test]
    public void TestFunction2()
    {
        baz.TestFunction2();
        Assert.Fail("autogenerated");
    }
}